Kevin
jubiman/Thesis-Game pull request #65
Opened 2021-10-09 13:10 UTC by Tyku031

inv kan geopend worden met e, animaties added, verder nog wat andere updates

2021-10-10 19:11 UTC, Sybsuper requested changes
Pls use tabs

2021-10-10 19:11 UTC, Sybsuper commented on core/UI/inventory.py
> +                                              (Settings.Game.WIDTH / 2 - 289 + 80 * (i - 16), Settings.Game.HEIGHT - 300))
kinda bad code, but working code so not complaining

2021-10-10 19:11 UTC, Sybsuper commented on core/inventory/inventory.py
> +        self.quantity = quant
waarom hier spaties en in inputhandler.py tabs

2021-10-10 23:20 UTC, Tyku031 commented on core/UI/inventory.py
> +                                              (Settings.Game.WIDTH / 2 - 289 + 80 * (i - 16), Settings.Game.HEIGHT - 300))
het kan altijd beter ja maar t werkt, maar eerlijk ik kan ook die itembar gwn zoveel opcleanen. but ja lol geen tijd.

2021-10-10 23:23 UTC, Tyku031 commented on core/inventory/inventory.py
> +        self.quantity = quant
is stom file reformatting ofzo ik weet niet precies, maar bij mij in mijn eigen code in pycharm staat het wel als tabs dus ik weet niet of ik er veel aan kan veranderen

2021-10-10 23:23 UTC, Tyku031 commented
die commit was iets kleins, had niks met de tabs te maken

2026-05-28 10:55 UTC, Tyku031 commented
no idea why this was still open lol

2026-05-28 10:55 UTC, closed without merging